-- ✅ Project Question - 1: Customer Lifetime Value Segmentation



-- Step 1: Aggregate total net revenue per customer
WITH customer_ltv AS 
(
    SELECT
        customerkey,                         -- Unique customer identifier
        full_name,                           -- Customer's full name
        SUM(total_revenue) AS total_net_revenue  -- Total revenue generated by this customer
    FROM
        cohort_analysis 
    GROUP BY 
        customerkey, 
        full_name
),

-- Step 2: Calculate revenue percentiles (25th and 75th) across all customers to segment LTV
customer_segments AS 
(
	SELECT
		PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_net_revenue) AS ltv_25, -- Bottom 25% cutoff
		PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY total_net_revenue) AS ltv_75  -- Top 25% cutoff
	FROM 
	    customer_ltv
),

-- Step 3: Assign each customer to a segment (High, Mid, Low) based on their total revenue
segement_values AS 
(
	SELECT 
		c.*, 
		CASE
			WHEN c.total_net_revenue < cs.ltv_25 THEN '3 - LOW '           -- Customers in the bottom 25%
			WHEN c.total_net_revenue >= cs.ltv_75 THEN '1 - High'         -- Top 25% customers
			ELSE '2 - MID'                                                -- Middle 50% customers
		END AS customer_segement
	FROM 
		customer_ltv c, 
		customer_segments cs
) 

-- Step 4: Summarize segment data - total revenue, customer count, and average revenue per customer
SELECT 
	customer_segement,                                                       -- LTV segment label
	'$ ' || SUM(total_net_revenue) AS total_ltv,                            -- Total revenue from segment
	COUNT(DISTINCT customerkey) AS total_customers,                         -- Number of unique customers in segment
	'$ ' || ROUND(SUM(total_net_revenue) / COUNT(DISTINCT customerkey)) AS avg_ltv -- Avg. revenue per customer
FROM
	segement_values 
GROUP BY 
	customer_segement
ORDER BY 
	customer_segement;                                                      -- Ordered from High to Low

	
	



-- ✅ Project Question - 2: Cohort-Based Revenue Analysis
	

	
-- This query shows how much each cohort (by first purchase year) contributed in terms of revenue
-- It considers only the revenue from first orders to understand customer acquisition quality

SELECT 
    cohort_year,                                                              -- Year when customers made their first purchase
    '$ ' || SUM(total_revenue) AS total_net_revenue,                         -- Total revenue from first purchases in that cohort
    COUNT(DISTINCT customerkey) AS total_unique_customers,                   -- Number of unique new customers in that cohort
    '$ ' || ROUND(SUM(total_revenue) / COUNT(DISTINCT customerkey)) AS customer_revenue -- Average revenue per new customer
FROM 
    cohort_analysis 
WHERE
    orderdate = first_purchase_date      -- We only want the very first order of each customer
GROUP BY
    cohort_year 
ORDER BY
    cohort_year;                         -- Display in chronological order

    
    



    
-- ✅ Project Question - 3: Churn Analysis by Cohort
    
    
    
-- Step 1: Identify the last order placed by each customer
WITH customer_last_purchase AS
(
	SELECT 
		customerkey, 
		full_name, 
		orderdate, 
		row_number() OVER(PARTITION BY customerkey ORDER BY orderdate DESC) AS rn, -- Rank to get the last purchase
		first_purchase_date,
		cohort_year 
	FROM 
		cohort_analysis
),

-- Step 2: Determine churn status based on the time since the last purchase
churned_customers AS 
(
	SELECT
		customerkey, 
		full_name, 
		first_purchase_date,
		orderdate AS last_purchase_date, 
		CASE
			-- If the last purchase was more than 6 months before the latest order in the dataset, mark as churned
			WHEN orderdate < (SELECT MAX(orderdate) FROM sales) - INTERVAL '6 months' THEN 'Churned'
			ELSE 'Active'
		END AS customer_status, 
		cohort_year 
	FROM
		customer_last_purchase 
	WHERE
		rn = 1  -- Only include the most recent (last) purchase per customer
		AND first_purchase_date < (SELECT MAX(orderdate) FROM sales) - INTERVAL '6 months' -- Exclude new customers who joined recently
) 

-- Step 3: Aggregate churn stats by cohort and status
SELECT 
	cohort_year,                                          -- Customer's acquisition year
	customer_status,                                      -- Either 'Active' or 'Churned'
	COUNT(customerkey) AS num_customers,                  -- Number of customers in this status
	SUM(COUNT(customerkey)) OVER(PARTITION BY cohort_year) AS total_customers, -- Total customers in the cohort
	ROUND(COUNT(customerkey) / SUM(COUNT(customerkey)) OVER(PARTITION BY cohort_year), 2) AS status_percentage -- % of status
FROM 
	churned_customers 
GROUP BY
	cohort_year,
	customer_status;
